---
- name: Disable cdrom repositories in sources.list
  when: ansible_os_family == "Debian"
  become: true
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb\s+cdrom:.*)$'
    replace: '# \1'

- name: Disable file:///cdrom repositories in sources.list
  when: ansible_os_family == "Debian"
  become: true
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(.*file:///cdrom.*)$'
    replace: '# \1'

- name: Set sysctl
  ansible.posix.sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: "1"
    sysctl_set: true
    state: present
    ignoreerrors: true

- name: Install packages Ubuntu/Debian
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - keepalived
      - haproxy
    state: present
    update_cache: yes

- name: Copy keepalived.conf to master
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0600'
  notify: restart keepalived

- name: Copy haproxy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  register: haproxy_conf
  notify: restart haproxy

- name: Validate HAProxy configuration
  become: true
  ansible.builtin.command: haproxy -f /etc/haproxy/haproxy.cfg -c
  register: haproxy_check
  changed_when: false
  failed_when: false

- name: Show HAProxy configuration check result
  ansible.builtin.debug:
    msg: "{{ haproxy_check.stderr_lines + haproxy_check.stdout_lines }}"
  when: haproxy_check.rc != 0

- name: Fail if HAProxy configuration is invalid
  ansible.builtin.fail:
    msg: "HAProxy configuration is invalid. Check the output above."
  when: haproxy_check.rc != 0

- name: Enable keepalived and haproxy
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - keepalived
    - haproxy
